// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmyrzhfijldhfaqvqfnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5teXJ6aGZpamxkaGZhcXZxZm5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2ODkxODgsImV4cCI6MjA3MjI2NTE4OH0.rdp35PKHKPAW-TXG3TnGhqEnc0RZLY2lPUbiLGf9N_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});